theme: jekyll-theme-architect

title: [Simple Java Project]
description: [Dummy test project]


show_downloads: false

links:
  download: http://glassfish.org/download
  mailinglist: http://groups.io
  doc: 

