theme: jekyll-theme-architect

title: [Simple Java Project]
description: [Dummy test project]


show_downloads: false

links:
  download: https://glassfish.java.net/download.html
  mailinglist: http://groups.io
  doc: 

