theme: jekyll-theme-architect

title: [GlassFish]
description: [Java EE Reference Implementation]

show_downloads: false

links:
  download: https://glassfish.java.net/download.html
  mailinglist: https://java.net/projects/glassfish/lists/users/archive
  issuetracker: "issues_url"
  source: https://java.net/projects/glassfish/sources/svn/show/trunk/main
  license: https://glassfish.java.net/license.html

