theme: jekyll-theme-architect

title: [Simple Java Project]
description: [SJP is a dummy test project on a branch]

show_downloads: true

mailinglist: [https://groups.io/g/The-Table-Top-Gaming-Society]
