theme: jekyll-theme-architect

title: [Simple Java Project]
description: [SJP is a dummy test project on a branch]

show_downloads: true

mailing_list: [https://groups.io/g/The-Table-Top-Gaming-Society]
