theme: jekyll-theme-architect

title: [Simple Java Project]
description: [Dummy test project]


show_downloads: false

links:
  download: https://glassfish.java.net/download.html
  mailinglist: https://java.net/projects/glassfish/lists/users/archive
  issuetracker: https://java.net/jira/browse/GLASSFISH
  source: http://github.com/jersey/jersey
  license: https://glassfish.java.net/license.html

